//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TearcVN.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProjectId { get; set; }
        public int FloorId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> LastUpdatedByUserID { get; set; }
    
        public virtual Floor Floor { get; set; }
        public virtual Product Product { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
